### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by websecnl** [n0mi1k/cacheblaster#1]
File "cacheblaster.py", line 56, in main
    parser.add_argument("-c", "--cachebuster", default=False, action=argparse.BooleanOptionalAction)
AttributeError: module 'argparse' has no attribute 'BooleanOptionalAction'

**Comment by n0mi1k** [comment]
This error occurs when Python 3.8 and below is used as the argparse module does not support `action=argparse.BooleanOptionalAction`. 

To fix this, use **Python 3.9** or replace the line with:
`parser.add_argument("-c", "--cachebuster", default=False, action="store_false")`

**Comment by n0mi1k** [comment]
This error occurs when Python 3.8 and below is used as the argparse module does not support `action=argparse.BooleanOptionalAction`. 

To fix this, use **Python 3.9** or replace the line with:
`parser.add_argument("-c", "--cachebuster", default=False, action="store_false")`
